### ISSUE TITLE
Main 진입점 진입 후 게임이 로드되지 않고 오류 발생

### ISSUE THREAD

**Issue by Ren-deRing** [simple-farming-game/simple_farming_game#18]
![image](https://github.com/simple-farming-game/simple_farming_game/assets/79672833/3fb74990-a746-43b5-9e95-75a88dc6673a)
lib/keyinput.py line 87
함수가 예상되지 않은 값을 반환함

**Comment by newkincode** [comment]
현재 개발이 중단되었지만 집가서 해결해보갰습니다
